### ISSUE TITLE
WebService::Rackspace::CloudFiles::Object::Iterator missing from cpan

### ISSUE THREAD

**Issue by shumphrey** [Htbaa/WebService-Rackspace-CloudFiles#21]
WebService::Rackspace::CloudFiles::Object::Iterator appears to be missing from cpan

https://metacpan.org/source/CKRAS/WebService-Rackspace-CloudFiles-2.00/lib/WebService/Rackspace/CloudFiles

This distribution is currently broken because https://metacpan.org/source/CKRAS/WebService-Rackspace-CloudFiles-2.00/lib/WebService/Rackspace/CloudFiles/Container.pm references a file that does not exist in the cpan distribution

**Comment by Htbaa** [comment]
Thanks for reporting. The Git repository has it. No clue why it got left out. I'll try releasing an update.

**Comment by Htbaa** [comment]
I created the dist with an outdated MANIFEST file. Just released 2.01 which should have this issue fixed. I've deleted the 2.00 release from CPAN because it's broken.
