### ISSUE TITLE
purge_cdn  in Object doesn't do an edge purge, it does a DELETE

### ISSUE THREAD

**Issue by jwrightecs** [Htbaa/WebService-Rackspace-CloudFiles#23]
The call uses the same URL as object delete, except it includes the X-Purge-Email.  It uses the storage endpoint and not the cdn management endpoint which is what enables edge purge 
( https://community.rackspace.com/products/f/25/t/4375 )

**Comment by Htbaa** [comment]
If you want this fixed please send me a pull request. I'm no longer (actively) working on this module. It's open for adoption.

**Comment by jwrightecs** [comment]
https://github.com/Htbaa/WebService-Rackspace-CloudFiles/pull/24
