### ISSUE TITLE
RackCDN API now returns 201 - Created instead of 204

### ISSUE THREAD

**Issue by jwrightecs** [Htbaa/WebService-Rackspace-CloudFiles#26]
The code in put / put_filename checks for response code 204 to set etag / size / content type, but the rackcdn api returns 201 which is more correct for a PUT

put and put_filename should check response.code == to 201 or 204

**Comment by Htbaa** [comment]
Can you provide a pull request?

**Comment by jwrightecs** [comment]
#27

**Comment by Htbaa** [comment]
Has been merged.

**Comment by Htbaa** [comment]
Versie 2.03 has been released. Currently being processed by CPAN.
